/*
 * This file was autogenerated by TinyMPC on Tue Feb 24 13:14:56 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
